// part-time/code/5063-nenad-ristov/react-app-exam/src/components/About/About.jsx
import './About.css'

const About = () =>{

    return(
        <>
        <h1>About</h1>
        <p>Name:</p>
        <h3>Nenad Ristov</h3>
        <p>Id:</p>
        <h3>5063</h3>
        <p>Id:</p>
        <h3>{new Date().getFullYear()}</h3>
        <p>Link to github:</p>
        <a href="https://github.com/nenadristov/uacs-internet-programming-exams/tree/part-time/part-time/code/5063-nenad-ristov"> Link</a><br />
        <p>Other Informations</p>
        <h4>Would have made it to look nicer design wise if I had  more time.</h4>
        </>
    )
}

export default About

// finals-2024-01-15/code/5197-elena-dimova/src/app/about/about.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrl: './about.component.css'
})
export class AboutComponent {
  currentYear: number = new Date().getFullYear();
}

<div>
    <h2>About</h2>
    <p>Name: Elena Dimova</p>
    <p>ID: 5197</p>
    <p>Current Year: {{ currentYear }}</p>
    <p>Github Repository: <a href="https://github.com/elenadimova1/uacs-internet-programming-exams" target="_blank">Link To My Github Repo</a></p>
</div>
