// part-time/code/5063-nenad-ristov/react-app-exam/src/components/About/About.jsx
import './About.css'

const About = () =>{

    return(
        <>
        <h1>About</h1>
        <p>Name:</p>
        <h3>Nenad Ristov</h3>
        <p>Id:</p>
        <h3>5063</h3>
        <p>Id:</p>
        <h3>{new Date().getFullYear()}</h3>
        <p>Link to github:</p>
        <a href="https://github.com/nenadristov/uacs-internet-programming-exams/tree/part-time/part-time/code/5063-nenad-ristov"> Link</a><br />
        <p>Other Informations</p>
        <h4>Would have made it to look nicer design wise if I had  more time.</h4>
        </>
    )
}

export default About

// finals-2024-01-15/code/5105-angela-cekovska/src/app/about/about.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrl: './about.component.css'
})
export class AboutComponent {
studentName: string = 'Your Name';
studentID: string = 'Your ID';
currentYear: number = new Date().getFullYear();
githubLink: string = "https://github.com/cekovskaa/uacs-internet-programming-exams/tree/main/finals-2024-01-15/docs";

}

<div>

    <h2>About Page</h2>
    <ul>

        <li>Name: {{ studentName }}</li>
        <li>ID: {{ studentID }}</li>
        <li>Current Year: {{ current year }}</li>
        <li>Repository: <a href="{{githubLink}}" target="_blank">{{githubLink}}></a></li>
        <li>This is about the page</li>
    </ul>
</div>
